<?php
/**
 * Created by PhpStorm.
 * User: morzi
 * Date: 05.05.2016
 * Time: 13:38
 */

/**
 * Implements hook_ctools_plugin_directory().
 */
function ctrader_panelbg_ctools_plugin_directory($module, $plugin) {
  if ($module == 'panels' && $plugin == 'styles') {
    return 'plugins/' . $plugin;
  }
}
function ctrader_panelbg_views_pre_render($view) {
  if ($view->name == 'condos_in_building') {
    if ($view->current_display == 'block_1') {
      $view->set_title($view->display['block_1']->display_title.' ('.$view->total_rows.')');
    }
    if ($view->current_display == 'block_2') {
      $view->set_title($view->display['block_2']->display_title.' ('.$view->total_rows.')');
    }
  }
}