<?php

/**
 * Implements hook_form_alter().
 */
function ctrader_fct_form_alter(&$form, &$form_state, $form_id) {
  switch ($form_id) {
    //Change price facet markup text.
    case 'search_api_ranges_block_slider_view_form_field_lp_dol__torcond':
      $form['text-range']['#markup'] = "<div class='facet-helper'><span id='price-min-value'>&#36;<span>" . $form_state['build_info']['args'][0]['from'] . "</span></span> - <span id='price-max-value'>&#36;<span>"  . $form_state['build_info']['args'][0]['to'] . "</span></span></div>";
      break;
    //Change price size facet markup text.
    case 'search_api_ranges_block_slider_view_form_field_sqft_range_max__torcond':
      $form['text-range']['#markup'] = "<div class='facet-helper'><span id='sqft-min-value'><span>" . $form_state['build_info']['args'][0]['from'] . "</span></span> - <span id='sqft-max-value'><span>"  . $form_state['build_info']['args'][0]['to'] . "</span></span>" . " " . t("SQFT") . "</div>";
      break;
  }
}

/**
 * Implements hook_block_info().
 */
function ctrader_fct_block_info() {
  //Create block to toggle map mode.
  $blocks['facet_map'] = array(
    'info' => t('Facet Map Block'),
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function ctrader_fct_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    //Create block to toggle map mode.
    case 'facet_map':
      $block['subject'] = '<h5 class="pane-title">' . t('Search by: ') . '</h5>';
      $block['content'] = '<div class="facet-map-block">';
      $block['content'] .= '<button class="facet-map-block-neighbourhood">' . t('Neighbourhood') . '</button>';
      $block['content'] .= '<button class="facet-map-block-map-search">' . t('Map Search') . '</button>';
      $block['content'] .= '</div>';
      break;
  }

  return $block;
}