<?php
/**
 * Created by PhpStorm.
 * User: aryan
 * Date: 03.04.16
 * Time: 15:50
 */

/**
 * Implements hook_menu().
 */
function ctrader_mls_menu() {
  $items['admin/config/mls'] = array(
    'title' => 'Mls integration page',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ctrader_mls_form'),
    'access arguments' => array('administer modules'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Form for configure integration drupal and mls.
 */
function ctrader_mls_form($form, &$form_state) {
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'test',
  );

  return $form;
}

/**
 * Implements hook_libraries_info().
 */
function ctrader_mls_libraries_info() {
  $libraries['torontomlsapi'] = array(
    'name' => 'Torontomlsapi',
    'vendor url' => 'https://github.com/tamtranvn2012/torontomlsapi',
    'download url' => 'https://github.com/tamtranvn2012/torontomlsapi/archive/master.zip',
    'version arguments' => array(
      'file' => 'phrets.php',
      'pattern' => '@version\s+([0-9a-zA-Z\.-]+)@',
    ),
    'files' => array(
      'php' => array(
        'phrets.php',
        'test.php',
        'test1.php',
      ),
    ),
  );

  return $libraries;
}
